# Generated by Django 5.1 on 2024-08-09 16:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('NIT', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idAuto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('mazda', 'Mazda'), ('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('bmw', 'BMW'), ('audi', 'Audi'), ('mercedes', 'Mercedes-Benz'), ('volkswagen', 'Volkswagen'), ('nissan', 'Nissan')], default='mazda', max_length=100)),
                ('modelo', models.IntegerField()),
                ('linea', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idCot', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime(2024, 8, 9, 16, 5, 20, 422764, tzinfo=datetime.timezone.utc))),
                ('NIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.cliente')),
                ('idAuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.vehiculo')),
            ],
        ),
    ]
