# Generated by Django 5.1 on 2024-08-09 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_cotizacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 16, 13, 12, 142807, tzinfo=datetime.timezone.utc)),
        ),
    ]
