# Generated by Django 5.1 on 2024-08-09 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_alter_cotizacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Ciudad', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='+502 2222-2222', max_length=25),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 16, 24, 25, 112243, tzinfo=datetime.timezone.utc)),
        ),
    ]
