# Generated by Django 5.1 on 2024-08-09 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_cliente_direccion_cliente_email_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 17, 1, 5, 301767, tzinfo=datetime.timezone.utc)),
        ),
    ]
