# Generated by Django 5.1 on 2024-08-09 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_alter_cotizacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='image',
            field=models.ImageField(null=True, upload_to='static/IMG'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 18, 40, 35, 649588, tzinfo=datetime.timezone.utc)),
        ),
    ]
